<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="page-main-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button type="button"
                    title="<?= $block->escapeHtml(__('Setup Amazon Store')); ?>"
                    class="action scalable primary"
                    onclick="location.href='<?= $block->escapeHtml(__($block->getUrl('channel/amazon/account_settings_credentials_index'))) ?>'">
                <span><?= $block->escapeHtml(__('Setup Amazon Store')) ?></span>
            </button>
        </div>
    </div>
</div>
<div class="help-button">
    <button type="button"
            class="action-default"
            onclick="window.open('<?= $block->getUserGuideUrl() . $block->getMainMenuUrl() ?>', '_blank')"
            id="helpButton" >
        <span><?= $block->escapeHtml(__('View User Guide')) ?></span>
    </button>
</div>
<div class="help-and-general-form">
    <?= $block->escapeHtml(__('Displays all Amazon stores with additional actions to setup a new Amazon store, delete an existing store, and more.')) ?>
</div>